### ISSUE TITLE
Website Request.

### ISSUE THREAD

**Issue by Domsicols** [MrBukLau/filter-lists#5]
Hi i really like your list but can include 9anime.to to your annoyance list and this anime site has so much pop ads and its very annoying. Thanks in advance. Been using your list for a while now and im using itnon adguard.

**Comment by MrBukLau** [comment]
Thank you for your compliment and for using my filter list!

Regarding your request, I assume that you are using iOS when browsing 9anime. If so, it would be difficult for me to block pop-under and pop-up advertisements on the mobile website of 9anime. I tried to use the filters that are used in [uBlock Origin](https://github.com/uBlockOrigin/uAssets), but they did not work when I added them to AdGuard, which meant that the pop-under and pop-up advertisements still appeared when using those filters. Because these filters did not work, it would be hard to make a filter that would work on iOS for 9anime. I could block the individual domains that serve the pop-under and pop-up advertisements, but they change frequently. It would be a time-consuming process for me to block them because a new domain could show up the very next day.
