### ISSUE TITLE
Filters make some reddit pages not scroll 

### ISSUE THREAD

**Issue by ghost** [MrBukLau/filter-lists#6]
On some reddit pages with the filters on I'm not able to scroll on the page it won't move when I remove the filters I can scroll just fine on all reddit pages I hope that you can fix this in a future update (ios adguard premium)

**Comment by MrBukLau** [comment]
Are there any specific Reddit pages where you have encountered this issue? I have been using these filters for awhile now, and I have not encountered this issue yet.

**Comment by ghost** [comment]
I opened up a reddit page in the telegram webview for safari and it wouldn't scroll when the filters are disabled I can scroll it just fine

**Comment by ghost** [comment]
Also it happens on certain reddit links it seems to happen randomly

**Comment by ghost** [comment]
So since you said you been using them for a while with no issue I figured maybe one of my other filters was interfering with it so I turned off all filters except yours and the issue still persists so it's the filters

**Comment by ghost** [comment]
I have experienced it on this reddit page 

https://www.reddit.com/r/YouShouldKnow/comments/enkhsq/ysk_that_with_the_webannoyances_ultralist_any/

**Comment by MrBukLau** [comment]
I went to that Reddit page, and I am able to scroll on that page using the filters. I did the same thing as you and turned off all the filter lists except the one with the Reddit filters, and I am still able to scroll on that page.

You mentioned that you have AdGuard premium. Did you enable the "Advanced Protection" option in the AdGuard application and in the iOS settings? If you did enable it, try turning off the AdGuard's web extension in the Safari section of the iOS settings and turning it back on because the web extension will sometimes stop working after an update. Please make sure to do it to the web extension and not the content blocker.

Here is a guide if you need help with it: https://adguard.com/kb/adguard-for-ios/web-extension/#how-to-enable-adguards-safari-web-extension

**Comment by ghost** [comment]
Alright so I did what you suggested and haven't encountered any scrolling problems however in the webview of telegram when a window is opened the reddit post still wouldn't scroll so I guess as a work around I open telegram links In safari i was wondering bro coukd you add removing the people also searched for this on google it randomly comes up and I accidentally click on the wrong link it's an annoyance at its most thank you for helping me trouble shoot this incident

**Comment by MrBukLau** [comment]
No problem! I will close this issue now. Please feel free to reopen this issue if it happens again or create a new issue if you experience any other issues.

From what I know, web extensions do not work in WebView because Apple does not allow it, so your workaround is the only available solution at the moment.

Regarding the Google annoyance, I will try to remove it, but I have not been able to get it to pop up on my device.
